name: version_banner
description: A banner that shows the current version or flavour of the app
version: 2.0.2
homepage: https://github.com/Vanethos/flutter_version_banner
issue_tracker: https://github.com/Vanethos/flutter_version_banner/issues

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
